### ISSUE TITLE
Backport?

### ISSUE THREAD

**Issue by CursedBM81** [JosiahFu/SuperHot#1]
There are no actual issues, I just wanted to ask if you could backport the mod for Fabric 1.20.1 so I can use it.

**Comment by ThePotatoArchivist** [comment]
I could look into it, I'd have to add a dependency on Time Stop Clock or a similar library because the current version uses the /tick functionality which wasn't added until 1.20.3

**Comment by ThePotatoArchivist** [comment]
Sorry, if you're still waiting on this issue I don't think this project will receive more support going forward.
